### PR TITLE
Optimize for StringComparison.Ordinal

### PR DESCRIPTION
**Pull request by NanaLich**
Now it will use equality operator(s) for equality comparing methods when the default StringComparison is set to Ordinal for Caseless:
-- I saw a random C# project written in Java style in which it uses string.Equals(string) & static string.Equals(string, string) everywhere...

Also slightly improved to accept attribute value contains white-spaces.

### CODE REVIEW

**Comment by NanaLich** [comment]
@SimonCropp could you take a look on this?

**Comment by SimonCropp** [comment]
is there no extra tests that are possible with this?

**Comment by NanaLich** [comment]
to be honest, I haven't figured out how the test stuff work for Fody
but i'll check for it, maybe a few hours

**Comment by NanaLich** [comment]
ok I now know how to add tests for the changes, but still don't know how to run the test

**Comment by SimonCropp** [comment]
they run with any nunit runner. eg resharper

**Comment by NanaLich** [comment]
The tests should work for changes now, tho they are not complete for all possible boundary conditions.
Consider improve the tests in the future.

**Comment by NanaLich** [comment]
hmmmm
what should i do with the TemplateClass?

**Comment by NanaLich** [comment]
@SimonCropp hello?
I'm sorry for bother you this way, but this change is a necessary for a few projects(those containing loads of ported Java code) i'm working on, so I personally hope it can apply as soon as possible...

**Comment by NanaLich** [comment]
cool!
can't wait to update dependency

**Comment by SimonCropp** [comment]
try now

**Comment by SimonCropp** [comment]
U on Twitter ?

**Comment by NanaLich** [comment]
why?
i don't use twitter much @licshee

**Pull request merged**
